---
 
- name: Ansible playbook for all our hosts
  hosts: all
  roles:
    - debian
  remote_user: debian
  become: yes

- name: Ansible playbook for configuring docker
  hosts: docker
  roles:
    - docker
  remote_user: debian
  become: yes

- name: Ansible playbook for configuring docker
  hosts: panel
  roles:
    - docker
    - panel
  remote_user: debian
  become: yes
