---
 
- name: Ansible playbook for all our hosts
  hosts: all
  roles:
    - debian
  remote_user: debian
  become: yes

- name: Ansible playbook for configuring docker
  hosts: docker
  roles:
    - docker
  remote_user: debian
  become: yes

- name: Ansible playbook for configuring panel docker compose
  hosts: panel
  roles:
    - docker
    - panel
  remote_user: debian
  become: yes

- name: Ansible Playbook for configuring homepage docker compose
  hosts: homepage
  roles:
   - docker
   - homepage
  remote_user: debian
  become: yes

- name: Ansible Playbook for configuring wings docker compose
  hosts: wings
  roles:
   - docker
   - wings
  remote_user: debian
  become: yes
  
   
