- name: create directory to house our docker-compose
  file: 
    path: /home/debian/homepage/ 
    state: directory
    owner: debian
    group: debian
  tags: homepage

- name: copy docker-compose.yml
  copy: 
    src: templates/docker.conf.j2 
    dest: /home/debian/homepage/docker-compose.yml
    owner: debian
    group: debian
  tags: homepage

- name: create docker_data directory
  file: 
    path: /home/debian/homepage/docker_data/ 
    state: directory
    owner: debian
    group: debian
  tags: homepage

- name: copy supporting files
  copy: 
    src: roles/homepage/templates/docker_data/ 
    dest: /home/debian/homepage/docker_data/
    owner: debian
    group: debian
  tags: homepage

- name: Run docker-compose
  docker_compose:
    project_src: /home/debian/homepage/
    build: no
  tags: homepage
